// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQKnH1Kvkrtzv7mqLFUEtzflytz7QVOTk',
    appId: '1:922825199080:android:e41615b474707e0aa0285d',
    messagingSenderId: '922825199080',
    projectId: 'mive-8e842',
    storageBucket: 'mive-8e842.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoBKyaRDLLbrQn_BXFB_GSOOn3VN3Tcms',
    appId: '1:922825199080:ios:73b110f73048afa3a0285d',
    messagingSenderId: '922825199080',
    projectId: 'mive-8e842',
    storageBucket: 'mive-8e842.appspot.com',
    iosClientId: '922825199080-55dac3e7bbv66s8rhinfpmr48c0ufj3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.mive',
  );
}
